In [4]:
!pip install xlrd

Collecting xlrd
  Downloading xlrd-2.0.2-py2.py3-none-any.whl.metadata (3.5 kB)
Downloading xlrd-2.0.2-py2.py3-none-any.whl (96 kB)
Installing collected packages: xlrd
Successfully installed xlrd-2.0.2

In [5]:
import pandas as pd

In [6]:
df = pd.read_excel(r"E:\datasets\survey.xls")
df

      Name Nationality     Sex  Age Handedness
0    Kathy         USA  Female   23      Right
1    Linda         USA  Female   18      Right
2    Peter         USA    Male   19      Right
3     John         USA    Male   22       Left
4   Fatima   Bangadesh  Female   31       Left
5    Kadir   Bangadesh    Male   25       Left
6   Dhaval       India    Male   35       Left
7   Sudhir       India    Male   31       Left
8   Parvir       India    Male   37      Right
9      Yan       China  Female   52      Right
10    Juan       China  Female   58       Left
11   Liang       China    Male   43       Left

In [9]:
pd.crosstab(df.Nationality,df.Handedness, margins = True)

Handedness   Left  Right  All
Nationality
Bangadesh       2      0    2
China           2      1    3
India           2      1    3
USA             1      3    4
All             7      5   12

In [8]:
pd.crosstab(df.Sex,df.Handedness)

Handedness  Left  Right
Sex
Female         2      3
Male           5      2

In [10]:
pd.crosstab(df.Nationality,[df.Sex,df.Handedness])

Sex         Female       Male
Handedness    Left Right Left Right
Nationality
Bangadesh        1     0    1     0
China            1     1    1     0
India            0     0    2     1
USA              0     2    1     1

In [13]:
pd.crosstab([df.Nationality,df.Sex],df.Handedness)

Handedness          Left  Right
Nationality Sex
Bangadesh   Female     1      0
            Male       1      0
China       Female     1      1
            Male       1      0
India       Male       2      1
USA         Female     0      2
            Male       1      1

In [15]:
import numpy as np
pd.crosstab(df.Sex,df.Handedness,values = df.Age, aggfunc = np.average)

Handedness  Left  Right
Sex
Female      44.5   31.0
Male        31.2   28.0